name: Generic
description: A generic issue
labels: []
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this is not a duplicate by looking through other open/closed issues
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description
    validations:
      required: true
