name: bloom-release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  bloom-release:
    if: startsWith(github.repository_owner, "LCAS")
    uses: LCAS/docker-dpkg-build/.github/workflows/bloom-release.yaml
    with:
      ros_distro: humble
      track: humble
      repo: "<ROSDISTRO REPO KEY>"
    secrets:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}      